name: Nancy Yoder

repo_names:
  - MAD-Polls
  - Test_StarWars

10-ux-ui-criticism:
  - https://vimeo.com/756205297
  - https://vimeo.com/manage/videos/756205342

11-models-from-data:
- https://github.com/nancyyoder/Test_StarWars

project-check-in-1:
- https://github.com/nancyyoder/ATLAS-iOS-Fall-22/issues/2
